name: Increment Version and Create Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    name: Increment Version and Create Tag
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Get Latest Tag
      id: get_latest_tag
      run: |
        git fetch --tags
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
        echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

    - name: Increment Version
      id: increment_version
      run: |
        version="${LATEST_TAG/v/}"
        IFS='.' read -r major minor patch <<< "$version"
        patch=$((patch + 1))
        new_version="v${major}.${minor}.${patch}"
        echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

    - name: Create and Push Tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag ${{ env.NEW_VERSION }}
        git push origin ${{ env.NEW_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.NEW_VERSION }}
        release_name: Release ${{ env.NEW_VERSION }}
        body: "Automated release for ${{ env.NEW_VERSION }}."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
