name: Update Version in pom.xml

on:
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Extract Release Tag
        id: extract_tag
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Update Version in pom.xml
        run: mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }}

      - name: Commit Updated Version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Update version to ${{ env.RELEASE_VERSION }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}